"""WP-24-implement-tenant-aware-abstract-data-access-layer

Revision ID: 05ae60324e0a
Revises: 1b96914bd5ad
Create Date: 2025-12-22 20:32:01.541501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ae60324e0a'
down_revision: Union[str, Sequence[str], None] = '1b96914bd5ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('container', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('document', sa.Column('direct_organization_id', sa.Integer(), nullable=True))
    op.add_column('document', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.alter_column('document', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'document', 'organization', ['direct_organization_id'], ['id'])
    op.add_column('driver', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('gps_device', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('location_log', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('organization', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('payment', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('price_quote', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('ship', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('ship_document', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('ship_item', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('ship_item_document', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('truck', sa.Column('deleted', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted')
    op.drop_column('truck', 'deleted')
    op.drop_column('ship_item_document', 'deleted')
    op.drop_column('ship_item', 'deleted')
    op.drop_column('ship_document', 'deleted')
    op.drop_column('ship', 'deleted')
    op.drop_column('price_quote', 'deleted')
    op.drop_column('payment', 'deleted')
    op.drop_column('organization', 'deleted')
    op.drop_column('location_log', 'deleted')
    op.drop_column('gps_device', 'deleted')
    op.drop_column('driver', 'deleted')
    op.drop_constraint(None, 'document', type_='foreignkey')
    op.alter_column('document', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('document', 'deleted')
    op.drop_column('document', 'direct_organization_id')
    op.drop_column('container', 'deleted')
    # ### end Alembic commands ###
