"""WP-42-document-upload-for-organization

Revision ID: 2fed385019fb
Revises: 44cc40b98555
Create Date: 2025-12-27 16:03:23.504632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fed385019fb'
down_revision: Union[str, Sequence[str], None] = '44cc40b98555'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("entity_type", sa.String(50), nullable=False))
    op.drop_constraint(op.f('document_direct_organization_id_fkey'), 'document', type_='foreignkey')
    op.drop_column('document', 'direct_organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('direct_organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('document_direct_organization_id_fkey'), 'document', 'organization', ['direct_organization_id'], ['id'])
    op.drop_column('document', 'entity_type')
    # ### end Alembic commands ###
