"""WP-8 adding fields to price quote table

Revision ID: 44cc40b98555
Revises: b06d5ad44ed9
Create Date: 2025-12-27 12:48:49.981563

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44cc40b98555'
down_revision: Union[str, Sequence[str], None] = 'b06d5ad44ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('price_quote', sa.Column('origin', sa.String(length=100), nullable=False))
    op.add_column('price_quote', sa.Column('destination', sa.String(length=100), nullable=False))
    op.add_column('price_quote', sa.Column('gross_weight_min', sa.Integer(), nullable=False))
    op.add_column('price_quote', sa.Column('gross_weight_max', sa.Integer(), nullable=False))
    op.add_column('price_quote', sa.Column('truck_type', sa.String(length=50), nullable=False))
    op.add_column('price_quote', sa.Column('container_size', sa.String(length=50), nullable=False))
    op.add_column('price_quote', sa.Column('axle_type', sa.String(length=50), nullable=True))
    op.add_column('price_quote', sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False))
    op.add_column('price_quote', sa.Column('currency', sa.String(length=3), nullable=False))
    op.add_column('price_quote', sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True))
    op.add_column('price_quote', sa.Column('valid_to', sa.DateTime(timezone=True), nullable=True))
    op.add_column('price_quote', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('price_quote', 'status')
    op.drop_column('price_quote', 'valid_to')
    op.drop_column('price_quote', 'valid_from')
    op.drop_column('price_quote', 'currency')
    op.drop_column('price_quote', 'amount')
    op.drop_column('price_quote', 'axle_type')
    op.drop_column('price_quote', 'container_size')
    op.drop_column('price_quote', 'truck_type')
    op.drop_column('price_quote', 'gross_weight_max')
    op.drop_column('price_quote', 'gross_weight_min')
    op.drop_column('price_quote', 'destination')
    op.drop_column('price_quote', 'origin')
    # ### end Alembic commands ###
