"""WP-40-document-upload-for-truck

Revision ID: 5ebdf0256de0
Revises: 2f1f07ddebd0
Create Date: 2025-12-25 22:12:09.423025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ebdf0256de0'
down_revision: Union[str, Sequence[str], None] = '2f1f07ddebd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'document_type',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'document_type',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
