"""WP-5-user-auth-and-onboarding

Revision ID: 7405a09625c3
Revises: 9ff3cc1a206a
Create Date: 2025-12-24 19:18:52.261088

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7405a09625c3'
down_revision: Union[str, Sequence[str], None] = '9ff3cc1a206a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('backoffice_user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.drop_table('backoffice')
    op.add_column('organization', sa.Column('name', sa.String(length=255), nullable=True))
    op.add_column('organization', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('organization', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('user', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('user', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('status', sa.Enum('ACTIVE', 'IN_ACTIVE', name='userstatusenum', native_enum=False, length=50), nullable=False))
    op.create_unique_constraint(None, 'user', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'status')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'email')
    op.drop_column('organization', 'phone')
    op.drop_column('organization', 'email')
    op.drop_column('organization', 'name')
    op.create_table('backoffice',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('backoffice_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('backoffice_pkey'))
    )
    op.drop_table('backoffice_user')
    # ### end Alembic commands ###
