"""WP-42-document-upload-for-organization

Revision ID: 8be47168dd32
Revises: b06d5ad44ed9
Create Date: 2025-12-27 11:22:45.180792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be47168dd32'
down_revision: Union[str, Sequence[str], None] = 'b06d5ad44ed9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document", sa.Column("entity_type", sa.String(50), nullable=False))
    op.drop_constraint(op.f('document_direct_organization_id_fkey'), 'document', type_='foreignkey')
    op.drop_column('document', 'direct_organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('direct_organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('document_direct_organization_id_fkey'), 'document', 'organization', ['direct_organization_id'], ['id'])
    op.drop_column('document', 'entity_type')
    # ### end Alembic commands ###

