"""WP-24-implement-tenant-aware-abstract-data-access-layer-fix

Revision ID: 954d98b21b33
Revises: 05ae60324e0a
Create Date: 2025-12-22 20:42:02.016125

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '954d98b21b33'
down_revision: Union[str, Sequence[str], None] = '05ae60324e0a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('container', 'deleted')
    op.drop_column('document', 'deleted')
    op.drop_column('driver', 'deleted')
    op.drop_column('gps_device', 'deleted')
    op.drop_column('location_log', 'deleted')
    op.drop_column('organization', 'deleted')
    op.drop_column('payment', 'deleted')
    op.drop_column('price_quote', 'deleted')
    op.drop_column('ship', 'deleted')
    op.drop_column('ship_document', 'deleted')
    op.drop_column('ship_item', 'deleted')
    op.drop_column('ship_item_document', 'deleted')
    op.drop_column('truck', 'deleted')
    op.drop_column('user', 'deleted')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('truck', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ship_item_document', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ship_item', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ship_document', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('ship', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('price_quote', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('payment', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('organization', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('location_log', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('gps_device', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('driver', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('document', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('container', sa.Column('deleted', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
