"""WP-7-implement-truck-management-ap-is

Revision ID: 9ff3cc1a206a
Revises: 882727a99327
Create Date: 2025-12-23 22:13:42.253441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ff3cc1a206a'
down_revision: Union[str, Sequence[str], None] = '882727a99327'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('truck', sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'OUT_OF_SERVICE', name='truckstatusenum', native_enum=False, length=50), nullable=False))
    op.add_column('truck', sa.Column('truck_type', sa.Enum('FLATBED', 'TRAILER', name='trucktypeenum', native_enum=False, length=50), nullable=False))
    op.add_column('truck', sa.Column('vin', sa.String(length=17), nullable=False))
    op.add_column('truck', sa.Column('plate_number', sa.String(length=20), nullable=False))
    op.add_column('truck', sa.Column('registration_date', sa.Date(), nullable=False))
    op.add_column('truck', sa.Column('gov_id', sa.String(length=50), nullable=True))
    op.add_column('truck', sa.Column('make', sa.String(length=100), nullable=True))
    op.add_column('truck', sa.Column('model', sa.String(length=100), nullable=True))
    op.add_column('truck', sa.Column('year', sa.Integer(), nullable=True))
    op.add_column('truck', sa.Column('color', sa.String(length=50), nullable=True))
    op.add_column('truck', sa.Column('capacity_quintal', sa.Integer(), nullable=False))
    op.add_column('truck', sa.Column('libre_key', sa.String(), nullable=True))
    op.create_index(op.f('ix_truck_plate_number'), 'truck', ['plate_number'], unique=True)
    op.create_index(op.f('ix_truck_vin'), 'truck', ['vin'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_truck_vin'), table_name='truck')
    op.drop_index(op.f('ix_truck_plate_number'), table_name='truck')
    op.drop_column('truck', 'libre_key')
    op.drop_column('truck', 'capacity_quintal')
    op.drop_column('truck', 'color')
    op.drop_column('truck', 'year')
    op.drop_column('truck', 'model')
    op.drop_column('truck', 'make')
    op.drop_column('truck', 'gov_id')
    op.drop_column('truck', 'registration_date')
    op.drop_column('truck', 'plate_number')
    op.drop_column('truck', 'vin')
    op.drop_column('truck', 'truck_type')
    op.drop_column('truck', 'status')
    # ### end Alembic commands ###
