"""Sync all tables with current models

Revision ID: aae6c42b0487
Revises: 0eebe507824a
Create Date: 2025-12-25 15:56:14.423454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aae6c42b0487'
down_revision: Union[str, Sequence[str], None] = '0eebe507824a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema - sync all tables with current models."""
    # Add deleted column to organization with default value for existing rows
    op.add_column('organization', sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    # Add deleted column to user with default value for existing rows
    op.add_column('user', sa.Column('deleted', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    
    # Make user.organization_id nullable (if not already)
    op.alter_column('user', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=True)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'organization_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('user', 'deleted')
    op.drop_column('organization', 'deleted')
    # ### end Alembic commands ###
