"""WP-30-gps-device-crud

Revision ID: b06d5ad44ed9
Revises: c944858e0683
Create Date: 2025-12-26 11:18:08.399276

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b06d5ad44ed9'
down_revision: Union[str, Sequence[str], None] = 'c944858e0683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('gps_device', sa.Column('external_device_id', sa.String(length=255), nullable=False))
    op.add_column('gps_device', sa.Column('imei_number', sa.String(length=50), nullable=False))
    op.add_column('gps_device', sa.Column('device_name', sa.String(length=255), nullable=True))
    op.add_column('gps_device', sa.Column('device_model', sa.String(length=255), nullable=True))
    op.add_column('gps_device', sa.Column('expire_date', sa.DateTime(timezone=True), nullable=False))
    op.add_column('gps_device', sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('gps_device', sa.Column('status', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_gps_device_external_device_id'), 'gps_device', ['external_device_id'], unique=True)
    op.create_index(op.f('ix_gps_device_imei_number'), 'gps_device', ['imei_number'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gps_device_imei_number'), table_name='gps_device')
    op.drop_index(op.f('ix_gps_device_external_device_id'), table_name='gps_device')
    op.drop_column('gps_device', 'status')
    op.drop_column('gps_device', 'last_synced_at')
    op.drop_column('gps_device', 'expire_date')
    op.drop_column('gps_device', 'device_model')
    op.drop_column('gps_device', 'device_name')
    op.drop_column('gps_device', 'imei_number')
    op.drop_column('gps_device', 'external_device_id')
    # ### end Alembic commands ###
