"""WP-16-add-driver-fields

Revision ID: b4ae0cb97ee1
Revises: 63a9cdc9fa6e
Create Date: 2025-12-24 15:24:54.980441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4ae0cb97ee1'
down_revision: Union[str, Sequence[str], None] = '63a9cdc9fa6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('driver', sa.Column('first_name', sa.String(length=100), nullable=True))
    op.add_column('driver', sa.Column('last_name', sa.String(length=100), nullable=True))
    op.add_column('driver', sa.Column('phone_number', sa.String(length=20), nullable=False))
    op.add_column('driver', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('driver', sa.Column('driver_license_number', sa.String(length=100), nullable=False))
    op.add_column('driver', sa.Column('status', sa.String(length=50), nullable=False))
    op.create_unique_constraint(None, 'driver', ['driver_license_number'])
    op.create_unique_constraint(None, 'driver', ['phone_number'])
    op.create_unique_constraint(None, 'driver', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'driver', type_='unique')
    op.drop_constraint(None, 'driver', type_='unique')
    op.drop_constraint(None, 'driver', type_='unique')
    op.drop_column('driver', 'status')
    op.drop_column('driver', 'driver_license_number')
    op.drop_column('driver', 'email')
    op.drop_column('driver', 'phone_number')
    op.drop_column('driver', 'last_name')
    op.drop_column('driver', 'first_name')
    # ### end Alembic commands ###
