"""WP-40-document-upload-for-truck

Revision ID: c944858e0683
Revises: 5ebdf0256de0
Create Date: 2025-12-25 22:12:53.346528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c944858e0683'
down_revision: Union[str, Sequence[str], None] = '5ebdf0256de0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('status', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document', 'status')
    # ### end Alembic commands ###
